version: '3.7'

services:
  grafana:
          image: grafana/grafana:latest
          ports:
                  - 3000:3000
  influxdb:
         image: influxdb:latest
         ports:
                 - 8087:8086
         environment:
                 - INFLUXDB_DB=corona_data
                 - INFLUXDB_USER=grafana
                 - INFLUXDB_ADMIN_ENABLED=true
                 - INFLUXDB_ADMIN_USER=admin
                 - INFLUXDB_ADMIN_PASSWORD=admin


